version: 0.0
os: linux
files:
  - source: /BlazorApp
    destination: /var/www/html/
hooks:
  BeforeInstall:
  - location: scripts/move_appspec.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
